apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Sowmyak12/multi-cloud-project.git
    targetRevision: main
    path: gitops/k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: taskflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
